FROM tangramor/slidev:playwright

COPY . /slidev

RUN npm install

RUN npx playwright install chromium

COPY ./src/generationEngine/slidev_integration/entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
