// tests/payment/subscriptionPlanCatalogScoping_test.go
//
// SECURITY RED tests: the generic SubscriptionPlan read endpoints leak hidden
// (non-catalog) plans to everyone.
//
// Background. `GET /api/v1/subscription-plans` and `GET
// /api/v1/subscription-plans/:id` are generated by the entity framework and
// registered with Security:false (see subscriptionPlanRegistration.go
// SwaggerConfig GetAll/GetOne Security:false + routeGenerator.go:108/119), so
// they are PUBLIC — no JWT. Today the SubscriptionPlan registration declares no
// read scoping, so the generic list/get handlers return EVERY plan to ANY
// caller, including unauthenticated ones. That exposes hidden plans
// (is_catalog=false, e.g. the bespoke Trainer plan) and their tiered pricing.
// The July hardening only covered the checkout path.
//
// Desired contract (pinned below as user-observable HTTP state):
//   (a) LIST as unauthenticated OR plain member → only is_catalog=true plans;
//       hidden plans absent from the payload and from Total.
//   (b) GET a hidden plan by id as unauthenticated OR member → 404 (NOT 403).
//       We deliberately pin 404, matching the platform's established
//       read-scoping convention in getEntity.go:54-64, where a non-owner fetch
//       returns "Entity Not Found" so existence is never disclosed. A 403 would
//       confirm the hidden plan exists; a 404 does not.
//   (c) Platform admin → LIST returns ALL plans incl. hidden; GET hidden by id
//       → 200 with the full model (regression guard for admin bypass).
//   (d) An entitlement HOLDER of a hidden plan still resolves it through the
//       dedicated EffectivePlanService path (this must NOT regress — scoping the
//       generic catalog route must not break plan display for holders).
//   (e) Zero-input: an empty catalog returns an empty list, not an error.
//
// Expected seam for the DEV (behaviour pinned here, not implementation): ride
// the platform's established generic read-scoping seam in
// src/entityManagement/routes/getEntities.go:112 and getEntity.go:54, which
// today keys off OwnershipConfig (owner-column equals caller) via
// ownerReadScope() (ownerReadScope.go:20). Catalog visibility is a boolean
// predicate (is_catalog=true for non-admins), NOT ownership, so the existing
// owner-column mechanism does not fit as-is. Crucially the catalog scope must
// differ from owner scope in one way: a MISSING userId (unauthenticated caller)
// must still see catalog plans, whereas owner scope fails closed to an empty
// page (getEntities.go:117-124). Recommendation: extend the same registration-
// driven read-scope seam in those two handlers with a catalog-visibility scope
// declared on the SubscriptionPlan registration (mirroring how ownerReadScope
// is declared via OwnershipConfig + admin bypass), rather than a bespoke
// controller — so the fix stays in the one read-scoping place the platform
// already funnels these decisions through.
//
// These tests drive the REAL generic router (controller.GetEntities /
// GetEntity) over the REAL registration.RegisterSubscriptionPlan, and assert
// USER-OBSERVABLE state (HTTP status + decoded JSON rows), never a mock call.
package payment_tests

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	entityManagementModels "soli/formations/src/entityManagement/models"
	ems "soli/formations/src/entityManagement/entityManagementService"
	controller "soli/formations/src/entityManagement/routes"
	registration "soli/formations/src/payment/entityRegistration"
	"soli/formations/src/payment/models"
	"soli/formations/src/payment/services"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/gorm"
)

// registerSubscriptionPlanForScoping registers the REAL SubscriptionPlan entity
// into the global registration service (the generic read handlers consult the
// global service to resolve entity ops + scoping) and unregisters it after the
// test, matching the payment-package precedent in
// upgradeSubscriptionReplacement_test.go.
func registerSubscriptionPlanForScoping(t *testing.T) {
	t.Helper()
	if _, ok := ems.GlobalEntityRegistrationService.GetEntityOps("SubscriptionPlan"); !ok {
		registration.RegisterSubscriptionPlan(ems.GlobalEntityRegistrationService)
		t.Cleanup(func() { ems.GlobalEntityRegistrationService.UnregisterEntity("SubscriptionPlan") })
	}
}

// subscriptionPlanScopingRouter builds a router that drives the generic
// list/get handlers for subscription-plans. Passing userID=="" and roles==nil
// simulates an UNAUTHENTICATED caller (the route is public, so no auth
// middleware runs in production either). The path segments must yield the
// "SubscriptionPlan" entity name via GetEntityNameFromPath.
func subscriptionPlanScopingRouter(db *gorm.DB, userID string, roles []string) *gin.Engine {
	gin.SetMode(gin.TestMode)
	gc := controller.NewGenericController(db, nil)
	r := gin.New()
	r.Use(func(c *gin.Context) {
		if userID != "" {
			c.Set("userId", userID)
		}
		if roles != nil {
			c.Set("userRoles", roles)
		}
		c.Next()
	})
	r.GET("/api/v1/subscription-plans/", func(c *gin.Context) { gc.GetEntities(c) })
	r.GET("/api/v1/subscription-plans/:id", func(c *gin.Context) { gc.GetEntity(c) })
	return r
}

type planListResponse struct {
	Data []struct {
		ID        string `json:"id"`
		Name      string `json:"name"`
		IsCatalog bool   `json:"is_catalog"`
	} `json:"data"`
	Total int64 `json:"total"`
}

// seedCatalogPlan creates an is_catalog=true plan.
func seedCatalogPlan(t *testing.T, db *gorm.DB, name string) *models.SubscriptionPlan {
	t.Helper()
	p := &models.SubscriptionPlan{
		BaseModel:       entityManagementModels.BaseModel{ID: uuid.New()},
		Name:            name,
		PriceAmount:     1200,
		Currency:        "eur",
		BillingInterval: "month",
		IsActive:        true,
		IsCatalog:       true,
	}
	require.NoError(t, db.Create(p).Error)
	return p
}

// seedHiddenPlan creates an is_catalog=false plan. GORM's Create skips the
// zero-value bool when the column carries gorm:"default:true", so is_catalog is
// forced false via a follow-up Update — the same workaround the existing
// subscriptionPlan_catalog_test.go documents.
func seedHiddenPlan(t *testing.T, db *gorm.DB, name string) *models.SubscriptionPlan {
	t.Helper()
	p := &models.SubscriptionPlan{
		BaseModel:       entityManagementModels.BaseModel{ID: uuid.New()},
		Name:            name,
		PriceAmount:     9900,
		Currency:        "eur",
		BillingInterval: "month",
		IsActive:        true,
	}
	require.NoError(t, db.Create(p).Error)
	require.NoError(t, db.Model(p).Update("is_catalog", false).Error)

	var fetched models.SubscriptionPlan
	require.NoError(t, db.First(&fetched, "id = ?", p.ID).Error)
	require.False(t, fetched.IsCatalog, "seed sanity: hidden plan must have is_catalog=false")
	return p
}

func doList(t *testing.T, r *gin.Engine) planListResponse {
	t.Helper()
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusOK, w.Code, "list should succeed; body=%s", w.Body.String())
	var resp planListResponse
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	return resp
}

func listContains(resp planListResponse, id string) bool {
	for _, d := range resp.Data {
		if d.ID == id {
			return true
		}
	}
	return false
}

// doListWithRawQuery lists with a caller-supplied raw query string so tests can
// probe query-param filter handling (e.g. an attacker-supplied is_catalog=false).
func doListWithRawQuery(t *testing.T, r *gin.Engine, rawQuery string) planListResponse {
	t.Helper()
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/?"+rawQuery, nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)
	require.Equal(t, http.StatusOK, w.Code, "list should succeed; body=%s", w.Body.String())
	var resp planListResponse
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &resp))
	return resp
}

// --- Filter-override defense: a caller cannot re-expose hidden plans by supplying
// their own is_catalog filter. The security-critical invariant — NO hidden plan
// is ever returned, and every returned row is a catalog plan — must hold for both
// the canonical column name and a case-variant param. This guards the
// filter-merge ordering against future refactors of the generic list handler.
//
// Note on the case variant: the catalog scope forces the filter on the exact
// column key ("is_catalog"), so it OVERRIDES a caller's is_catalog=false (the
// catalog plan stays visible). A case-variant key like IsCatalog=false is not
// overridden and survives as an additional AND predicate — it can only NARROW
// the result (here to zero rows), never widen it to hidden plans. Both cases are
// therefore safe; only the canonical param keeps the catalog plan visible, so
// the "catalog present / Total" assertions are pinned only there.
func TestSubscriptionPlanScoping_ListWithCatalogFilterOverride_NeverExposesHiddenPlans(t *testing.T) {
	registerSubscriptionPlanForScoping(t)

	for _, rawQuery := range []string{"is_catalog=false", "IsCatalog=false"} {
		t.Run(rawQuery, func(t *testing.T) {
			db := freshTestDB(t)
			catalog := seedCatalogPlan(t, db, "Solo")
			hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

			r := subscriptionPlanScopingRouter(db, "", nil) // unauthenticated
			resp := doListWithRawQuery(t, r, rawQuery)

			// Security-critical: hidden plans must never appear, and every returned
			// row must be a catalog plan — regardless of the caller-supplied filter.
			assert.False(t, listContains(resp, hidden.ID.String()),
				"a caller-supplied %q filter must NOT re-expose hidden plans — the catalog scope must win", rawQuery)
			for _, d := range resp.Data {
				assert.True(t, d.IsCatalog,
					"every returned row must be a catalog plan despite the %q filter; got hidden plan %q", rawQuery, d.Name)
			}

			// The canonical column-name filter is overridden by the scope, so the
			// catalog plan stays visible; the case variant may narrow to zero rows.
			if rawQuery == "is_catalog=false" {
				assert.True(t, listContains(resp, catalog.ID.String()),
					"catalog plans must remain visible when the caller's filter uses the real column name")
				assert.Equal(t, int64(1), resp.Total,
					"Total must stay scoped to the single catalog plan")
			}
		})
	}
}

// --- (a) LIST hides non-catalog plans from unauthenticated + member ---------

func TestSubscriptionPlanScoping_ListAsUnauthenticated_HidesNonCatalogPlans(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	catalog := seedCatalogPlan(t, db, "Solo")
	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "", nil) // unauthenticated
	resp := doList(t, r)

	assert.True(t, listContains(resp, catalog.ID.String()), "public catalog plan must be listed")
	assert.False(t, listContains(resp, hidden.ID.String()),
		"hidden (is_catalog=false) plan must NOT be exposed to an unauthenticated caller")
	assert.Equal(t, int64(1), resp.Total, "Total must count only catalog plans")
}

func TestSubscriptionPlanScoping_ListAsMember_HidesNonCatalogPlans(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	catalog := seedCatalogPlan(t, db, "Solo")
	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "member-1", []string{"member"})
	resp := doList(t, r)

	assert.True(t, listContains(resp, catalog.ID.String()), "member must see catalog plans")
	assert.False(t, listContains(resp, hidden.ID.String()),
		"hidden plan must NOT be exposed to a plain member")
	assert.Equal(t, int64(1), resp.Total, "Total must count only catalog plans")
}

// --- (b) GET a hidden plan by id → 404 for unauthenticated + member ---------

func TestSubscriptionPlanScoping_GetHiddenByIdAsUnauthenticated_Returns404(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "", nil)
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/"+hidden.ID.String(), nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code,
		"unauthenticated GET of a hidden plan by id must be 404, got %d; body=%s", w.Code, w.Body.String())
	assert.NotContains(t, w.Body.String(), "Trainer Bespoke",
		"404 body must not disclose the hidden plan's name")
	assert.NotContains(t, w.Body.String(), "9900",
		"404 body must not disclose the hidden plan's pricing")
}

func TestSubscriptionPlanScoping_GetHiddenByIdAsMember_Returns404(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "member-1", []string{"member"})
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/"+hidden.ID.String(), nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	assert.Equal(t, http.StatusNotFound, w.Code,
		"member GET of a hidden plan by id must be 404, got %d; body=%s", w.Code, w.Body.String())
	assert.NotContains(t, w.Body.String(), "Trainer Bespoke",
		"404 body must not disclose the hidden plan's name")
}

// A catalog plan by id stays publicly fetchable (guard: scoping must not hide
// the plans the pricing page legitimately needs).
func TestSubscriptionPlanScoping_GetCatalogByIdAsUnauthenticated_Returns200(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	catalog := seedCatalogPlan(t, db, "Solo")

	r := subscriptionPlanScopingRouter(db, "", nil)
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/"+catalog.ID.String(), nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code,
		"catalog plan must stay publicly fetchable; body=%s", w.Body.String())
	assert.Contains(t, w.Body.String(), "Solo", "catalog plan payload must include its name")
}

// --- (c) Admin sees everything (regression guard for admin bypass) ----------

func TestSubscriptionPlanScoping_ListAsAdmin_ReturnsAllPlans(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	catalog := seedCatalogPlan(t, db, "Solo")
	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "admin-1", []string{"administrator"})
	resp := doList(t, r)

	assert.True(t, listContains(resp, catalog.ID.String()), "admin must see catalog plans")
	assert.True(t, listContains(resp, hidden.ID.String()), "admin must see hidden plans")
	assert.Equal(t, int64(2), resp.Total, "admin Total must count all plans")
}

func TestSubscriptionPlanScoping_GetHiddenByIdAsAdmin_Returns200(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	r := subscriptionPlanScopingRouter(db, "admin-1", []string{"administrator"})
	req := httptest.NewRequest("GET", "/api/v1/subscription-plans/"+hidden.ID.String(), nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	require.Equal(t, http.StatusOK, w.Code,
		"admin GET of a hidden plan by id must be 200; body=%s", w.Body.String())
	assert.Contains(t, w.Body.String(), "Trainer Bespoke",
		"admin must receive the hidden plan's full model")
}

// --- (d) Entitlement holder still resolves the hidden plan (must NOT regress) -

// A holder assigned a hidden plan must still see it through the dedicated
// EffectivePlanService path. This path never goes through the scoped generic
// catalog route, so it is green today and must stay green after the fix — a
// guard proving catalog scoping does not break entitlement display for holders.
func TestSubscriptionPlanScoping_HolderResolvesHiddenPlanViaEffectivePlan(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	hidden := seedHiddenPlan(t, db, "Trainer Bespoke")

	const holderID = "holder-user-1"
	createUserSubscription(t, db, holderID, hidden)

	svc := services.NewEffectivePlanService(db)
	result, err := svc.GetUserEffectivePlan(holderID, nil)
	require.NoError(t, err)
	require.NotNil(t, result)
	require.NotNil(t, result.Plan, "holder must resolve an effective plan")
	assert.Equal(t, hidden.ID, result.Plan.ID,
		"entitlement holder must still resolve the hidden plan they are assigned")
	assert.Equal(t, "Trainer Bespoke", result.Plan.Name,
		"the hidden plan's data must still flow to its holder")
}

// --- (e) Zero-input: an empty catalog returns an empty list, not an error ---

func TestSubscriptionPlanScoping_EmptyCatalog_ReturnsEmptyList(t *testing.T) {
	registerSubscriptionPlanForScoping(t)
	db := freshTestDB(t)

	r := subscriptionPlanScopingRouter(db, "", nil) // unauthenticated, empty catalog
	resp := doList(t, r)

	assert.Equal(t, int64(0), resp.Total, "empty catalog must report Total=0")
	assert.Empty(t, resp.Data, "empty catalog must return an empty data slice, not an error")
}
