package services

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"soli/formations/src/scenarios/models"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// The shell form a container sources. Values are written out in full rather than
// composed from one another: there is nothing to gain from re-deriving in shell
// what has already been derived here, and a composed file only works if it is
// ordered parents-first to begin with.
const lexiconHeader = `# Generated by ocf-core from the scenario's lexicon — do not edit.
#
# W_* is what an object is called; P_* is where it lives; T_* is text found
# inside the world's files. Scripts compose these rather than naming rooms, so
# one script serves every language.
`

// LexiconContainerPath is where the generated file lands. Machinery: the same
// in every locale, and the one thing every script has to agree on.
const LexiconContainerPath = "/etc/ocf-lexicon.sh"

// Values needing no quoting. A slash is not special in an assignment, so paths
// are written plainly; anything else — a space, an accent — is quoted, which is
// what keeps a lexicon that should not contain those from silently splitting.
var shellSafeName = regexp.MustCompile(`^[A-Za-z0-9_./*-]+$`)

// GenerateLexicon renders one locale's vocabulary as shell.
//
// Refuses rather than falls back when a name is missing. Prose that falls back
// is merely untranslated; a path that falls back points somewhere this learner's
// disk does not have, and the step that sends them there cannot be passed.
func GenerateLexicon(db *gorm.DB, scenarioID uuid.UUID, locale string) (string, error) {
	entries, names, err := loadLexicon(db, scenarioID)
	if err != nil {
		return "", err
	}
	if len(entries) == 0 {
		return "", nil
	}

	ordered, err := orderParentsFirst(entries)
	if err != nil {
		return "", err
	}

	// A key occupying more than one place needs its paths told apart, and one
	// occupying a single place should not be burdened with a parent in its name.
	positions := map[string]int{}
	for _, entry := range ordered {
		positions[entry.Key]++
	}

	paths := map[string]string{}
	emittedName := map[string]bool{}
	var placeLines, tokenLines []string

	for _, entry := range ordered {
		name, ok := names[entry.ID][locale]
		if !ok || name == "" {
			return "", fmt.Errorf("lexicon: %q has no name in %q", entry.Key, locale)
		}

		switch entry.Kind {
		case "token":
			tokenLines = append(tokenLines, fmt.Sprintf("T_%s=%s", entry.Key, shellQuote(name)))
			continue
		case "message":
			// What a check says when it refuses. Same shape as a token — a key,
			// one wording per language, nowhere in the world — but read by a
			// person rather than grepped for, which is why it keeps its own
			// prefix instead of being filed among the world's text.
			tokenLines = append(tokenLines, fmt.Sprintf("M_%s=%s", entry.Key, shellQuote(name)))
			continue
		}

		if !emittedName[entry.Key] {
			emittedName[entry.Key] = true
			placeLines = append(placeLines, fmt.Sprintf("W_%s=%s", entry.Key, shellQuote(name)))
		}
		if entry.Kind == "stem" {
			// A stem names a fragment shared by other objects; it is nowhere in
			// particular, so it has no path.
			continue
		}

		parent := paths[entry.ParentKey]
		full := parent + "/" + name

		slot := entry.Key
		if positions[entry.Key] > 1 && entry.ParentKey != "" {
			slot = entry.ParentKey + "_" + entry.Key
		}
		paths[slot] = full
		placeLines = append(placeLines, fmt.Sprintf("P_%s=%s", slot, shellQuote(full)))
	}

	out := []string{lexiconHeader, "OCF_LOCALE=" + locale, ""}
	out = append(out, placeLines...)
	if len(tokenLines) > 0 {
		out = append(out, "")
		out = append(out, tokenLines...)
	}
	return strings.Join(out, "\n") + "\n", nil
}

func loadLexicon(db *gorm.DB, scenarioID uuid.UUID) ([]models.ScenarioLexiconEntry, map[uuid.UUID]map[string]string, error) {
	var entries []models.ScenarioLexiconEntry
	if err := db.Where("scenario_id = ?", scenarioID).
		Order("position ASC").Find(&entries).Error; err != nil {
		return nil, nil, fmt.Errorf("load lexicon: %w", err)
	}
	if len(entries) == 0 {
		return nil, nil, nil
	}

	ids := make([]uuid.UUID, len(entries))
	for i, e := range entries {
		ids[i] = e.ID
	}
	var rows []models.ScenarioLexiconName
	if err := db.Where("entry_id IN ?", ids).Find(&rows).Error; err != nil {
		return nil, nil, fmt.Errorf("load lexicon names: %w", err)
	}

	names := map[uuid.UUID]map[string]string{}
	for _, row := range rows {
		if names[row.EntryID] == nil {
			names[row.EntryID] = map[string]string{}
		}
		names[row.EntryID][row.Locale] = row.Name
	}
	return entries, names, nil
}

// orderParentsFirst sorts so every entry follows the one it composes from.
//
// Position alone is not enough: it orders siblings, and nothing stops an editor
// from listing a room before the building it is in. A child emitted first would
// compose against an unset parent and quietly become a path one level short —
// which reads as a step that cannot be passed, not as a broken lexicon.
func orderParentsFirst(entries []models.ScenarioLexiconEntry) ([]models.ScenarioLexiconEntry, error) {
	byKey := make(map[string]models.ScenarioLexiconEntry, len(entries))
	for _, e := range entries {
		byKey[e.Key] = e
	}

	var ordered []models.ScenarioLexiconEntry
	placed := map[string]bool{}

	// Placement is tracked per place, not per key: an object that sits in two
	// rooms is two positions of one object, and keying on the name alone would
	// silently drop the second — leaving a mission moving something to a
	// destination the world never built.
	slotOf := func(e models.ScenarioLexiconEntry) string { return e.ParentKey + "/" + e.Key }

	var place func(models.ScenarioLexiconEntry, map[string]bool) error
	place = func(entry models.ScenarioLexiconEntry, seen map[string]bool) error {
		if placed[slotOf(entry)] {
			return nil
		}
		if seen[entry.Key] {
			return fmt.Errorf("lexicon: %q is inside itself", entry.Key)
		}
		seen[entry.Key] = true

		if entry.ParentKey != "" {
			parent, ok := byKey[entry.ParentKey]
			if !ok {
				return fmt.Errorf("lexicon: %q sits inside %q, which does not exist", entry.Key, entry.ParentKey)
			}
			if err := place(parent, seen); err != nil {
				return err
			}
		}
		placed[slotOf(entry)] = true
		ordered = append(ordered, entry)
		return nil
	}

	sorted := append([]models.ScenarioLexiconEntry(nil), entries...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Position < sorted[j].Position })
	for _, entry := range sorted {
		if err := place(entry, map[string]bool{}); err != nil {
			return nil, err
		}
	}
	return ordered, nil
}

func shellQuote(value string) string {
	if shellSafeName.MatchString(value) {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

// ValidateLexicon reports every problem at once.
//
// All of them are failures that would otherwise be silent. A missing name stops
// the world building; an accented or spaced place name is typed by someone who
// has not met quoting; two siblings sharing a name are one directory, and the
// world quietly loses a room rather than failing to build.
//
// Reported rather than refused, because this runs while someone is editing: a
// half-finished lexicon is the normal state of one being written.
func ValidateLexicon(db *gorm.DB, scenarioID uuid.UUID) ([]string, error) {
	var scenario models.Scenario
	if err := db.First(&scenario, "id = ?", scenarioID).Error; err != nil {
		return nil, err
	}
	locales, err := scenario.GetLocales()
	if err != nil {
		return nil, err
	}
	if len(locales) == 0 {
		locales = []string{scenario.DefaultLocale}
	}

	entries, names, err := loadLexicon(db, scenarioID)
	if err != nil || len(entries) == 0 {
		return nil, err
	}

	var problems []string
	for _, locale := range locales {
		if locale == "" {
			continue
		}
		siblings := map[string]string{}

		for _, entry := range entries {
			name, ok := names[entry.ID][locale]
			if !ok || name == "" {
				problems = append(problems, fmt.Sprintf("%s: %s has no name", locale, entry.Key))
				continue
			}

			// Only places are typed as paths. Tokens are read out of files and
			// messages are read by a person, so both carry accents and
			// punctuation freely — flagging those would train people to ignore
			// this.
			if entry.Kind != "token" && entry.Kind != "message" && !shellSafeName.MatchString(name) {
				problems = append(problems, fmt.Sprintf(
					"%s: %s is called %q, which cannot be typed as a path", locale, entry.Key, name))
			}

			if entry.Kind == "token" || entry.Kind == "message" {
				continue
			}
			slot := entry.ParentKey + "/" + name
			if other, clash := siblings[slot]; clash {
				problems = append(problems, fmt.Sprintf(
					"%s: %s and %s are both called %q in the same place", locale, other, entry.Key, name))
				continue
			}
			siblings[slot] = entry.Key
		}
	}
	return problems, nil
}
